### PR TITLE
Feature/71 setup front end linter

### PR DESCRIPTION
**Pull request by leandertolksdorf**
Done:
- Setup ESLint and .eslintrc.json
- Setup Prettier and .prettierrc
- Lint and format legacy code

Please install the Prettier extension in your IDE and configure it to auto-format on every save.
This will ensure a consistent formatting.

You can run the lint script manually with `npm run lint`

### CODE REVIEW

**Review by jandegen — APPROVED** [review]
Hard to read as everything changed

**Review by PhlppKrmr — APPROVED** [review]
LGTM!
Only in the *.svelte files there's no linting on save (have to select "Format Document" to make sure it applies lints), but that might be on my part.

**Review by motschel123 — APPROVED** [review]
LGTM.
I have the same Issue regarding .svelte files.

**Comment by leandertolksdorf** [comment]
@motschel123 @PhlppKrmr @jandegen 
I updated the scripts. Now to run eslint: `npm run lint || lint:fix`, for prettier: `npm run prettier || prettier:fix` and to run everything: `npm run format`.
The prettier-scripts also run on .svelte files.
To configure VSCode to auto-format .svelte files on save, you have to add this to your settings.json:
```
"[svelte]": {"editor.defaultFormatter": "svelte.svelte-vscode"}
```

**Review by jenswaechtler — APPROVED** [review]
It's relatively slow if you use `npm run format`, but it works. It is best to enter the new dependencies directly in the _bill of materials_ so that it is not forgotten.

**Review by motschel123 — APPROVED** [review]
Works fine now 👍

**Pull request merged**
