### PR TITLE
first working draft of implementation for #80 signal head

### PR DESCRIPTION
**Pull request by nicolaskolbenschlag**
Signed-off-by: nicolaskolbenschlag <nicolas.kolbenschlag@googlemail.com>

### CODE REVIEW

**Review by leandertolksdorf — APPROVED** [review]

**Review by PhlppKrmr — APPROVED** [review]
Looks good so far, make sure to include tests to fulfill DoD.

One concern I have (not really scope of this issue) is performance. The signal head is once again computed on the CPU (in JS), we should look into how/if we can outsource some stuff onto the GPU.

**Review by PhlppKrmr — CHANGES_REQUESTED** [review]
Can't retrospectively change from "Approve" to "Request changes" (afaik). This is only to indicate that tests are missing :)

**Comment by motschel123** [comment]
> Can't retrospectively change from "Approve" to "Request changes" (afaik). This is only to indicate that tests are missing :)

As far as the changes only implement logic inside the plot, it is not quite possible to test for that in cypress, same applies for cursor feature.
E.g. in your feature for line thickness you only could test the presence of the switches and not the logic displaying the thick lines.

**Review by motschel123 — APPROVED** [review]
LGTM. 
As far as tests go it not really possible to test for plot only logic right now.

**Pull request merged**
