### PR TITLE
Timesweep Indicator #151

### PR DESCRIPTION
**Pull request by nicolaskolbenschlag**
Signed-off-by: nicolaskolbenschlag <nicolas.kolbenschlag@googlemail.com>

### CODE REVIEW

**Review by motschel123 — CHANGES_REQUESTED** [review]
We should specify the units somewhere. The example in the issue is secs/div which doesn't map the current implementation (e.g. current 0.5 should be 2 secs/div).

**Comment by nicolaskolbenschlag** [comment]
> We should specify the units somewhere. The example in the issue is secs/div which doesn't map the current implementation (e.g. current 0.5 should be 2 secs/div).

Screenshot from 2023-01-02 08-37-47
I think we need the refactor the overall layout if we want to add more as any new character causes a line break

**Comment by PhlppKrmr** [comment]
Regarding the above comments, look at my PR (#157), there we have a complete restructuring of the layout. Especially the point of displaying the value should be extremely easy using it.

Additionally, I'd suggest we add the units to the header (e.g. "Time Sweep [sec/div]")

**Comment by nicolaskolbenschlag** [comment]
> Regarding the above comments, look at my PR (#157), there we have a complete restructuring of the layout. Especially the point of displaying the value should be extremely easy using it.
> 
> Additionally, I'd suggest we add the units to the header (e.g. "Time Sweep [sec/div]")

The unit is for time-sweep is just × (e.g., ×2). I think, we do not know the actual speed expressed as pixels per time, as this dependent on the values delivered by the generator.

**Comment by nicolaskolbenschlag** [comment]
> > > Regarding the above comments, look at my PR (#157), there we have a complete restructuring of the layout. Especially the point of displaying the value should be extremely easy using it.
> > > Additionally, I'd suggest we add the units to the header (e.g. "Time Sweep [sec/div]")
> > 
> > 
> > The unit is for time-sweep is just × (e.g., ×2). I think, we do not know the actual speed expressed as pixels per time, as this dependent on the values delivered by the generator.
> 
> Spoke with Wieland about it, he also thinks the unit for the time sweep should be [sec/div], just as previously mentioned

Okay I see. I just currently see one difficulty with this, because in our implementation, the one div is added with one update from the generator. Hence, the time/div would be dependent on the (sending frequency of the) generator and only could be derived empirically/approximally. Currently, our time-sweep does control something like divs/update rater then time/div.

**Comment by PhlppKrmr** [comment]
> 

Good point, @nicolaskolbenschlag. I'd suggest not including the units for this sprint and asking Mr. Eckert if he wants/needs those to be displayed in the next JF. What do you think?

**Review by jenswaechtler — APPROVED** [review]

**Review by PhlppKrmr — CHANGES_REQUESTED** [review]
Can/will only approve when dev is merged in here to make sure everything works with new layout. Shouldn't be much to resolve :)

**Pull request closed without merging**
