### PR TITLE
Feature/#171 responsive web design

### PR DESCRIPTION
**Pull request by PhlppKrmr**
Let me know if the layout works as expected on your devices and of course, if you have any suggestions for improvement (both code & look) :)

### CODE REVIEW

**Comment by PhlppKrmr** [comment]
Please also lmk which button you'd prefer for the distribution (ignore the hover effect and size differences):
1) 
image
2) 
image

**Review by jandegen — APPROVED** [review]
Looks good.
Any specific reason why you removed the "mui" prefix? I followed that pattern in other PRs.

Also I can would expect merge issues with [Feature/#168 Rework UI for presets](https://github.com/amosproj/amos2022ws03-software-oscilloscope/pull/182) as the preset stuff changed a bit

**Comment by jandegen** [comment]
> Please also lmk which button you'd prefer for the distribution (ignore the hover effect and size differences): 1) image 2) image

Thumps up reaction for icon 1!
Party reation for icon 2!

**Review by nicolaskolbenschlag — CHANGES_REQUESTED** [review]
The sliders are not anymore visible.

image

**Comment by PhlppKrmr** [comment]
> The sliders are not anymore visible.
> 
> image

What broswer are you using here?

**Comment by nicolaskolbenschlag** [comment]
> > The sliders are not anymore visible.
> > image
> 
> What broswer are you using here?

Chrome

**Comment by PhlppKrmr** [comment]
> > > The sliders are not anymore visible.
> > > image
> > 
> > 
> > What broswer are you using here?
> 
> Chrome

Danke dir, @nicolaskolbenschlag !
Dennoch sehr strange, bei mir war bei Edge, Brave, Chrome und Firefox alles sichtbar. Hab nochmal das styling angepasst, sollte jetzt auch für dich sichtbar sein. Lmk wenn nicht :)

**Comment by PhlppKrmr** [comment]
> Looks good. Any specific reason why you removed the "mui" prefix? I followed that pattern in other PRs.
> 
> Also I can would expect merge issues with [Feature/#168 Rework UI for presets](https://github.com/amosproj/amos2022ws03-software-oscilloscope/pull/182) as the preset stuff changed a bit

Removed it cause we no longer use only mui (material ui) icons. Didn't want it to be confusing and inconsistent going forward. Hope I didn't break too much on your end ;)

**Review by nicolaskolbenschlag — COMMENTED** [review]
Mmh, really strange. I tested it with Chrome and Edge and it still looks like this. Do the others also have this problem?

image

**Review by jandegen — APPROVED** [review]

**Comment by jandegen** [comment]
> > > > The sliders are not anymore visible.
> > > > image
> > > 
> > > 
> > > What broswer are you using here?
> > 
> > 
> > Chrome
> 
> Thanks, @nicolaskolbenschlag ! Really strange, I tested it in Edge, Brave, Chrome and Firefox and for me they are visible. Adapted styling once again, lmk if you now see them.
> 
> Edit: Translated comment from German to English

Mine looks fine: (Tested on Edge) 

image
image

**Review by jandegen — APPROVED** [review]

**Review by rabbit-zero — APPROVED** [review]
works fine for me in opera in dark mode and light mode

**Review by nicolaskolbenschlag — APPROVED** [review]

**Pull request merged**
